rotate_integer.o: rotate_integer.cc
	g++ -c rotate_integer.cc
rotate_integer: rotate_integer.o
	g++ -o rotate_integer rotate_integer.o
clean: rotate_integer rotate_integer.o
	rm rotate_integer rotate_integer.o
